### ==== Web Server Playbook ==== ###
# Installs nginx and certbot
# Configures UFW default policies
# Allows HTTP traffic
# Allows HTTPS traffic
# Configures UFW to allow web traffic

---
- name: Configure Web Server
  hosts: servers
  become: true
  gather_facts: false
  vars:
    ansible_user: "{{ user_devops }}"
    ansible_ssh_private_key_file: "{{ ssh_private_key }}"
    ansible_port: "{{ prod_ssh_port }}"
  roles:
    - role: webserver
      tags: ['webserver']
