### ==== Security Playbook ==== ###
#                                 #
# Run only once after OS install  #
# Wrapper for initial playbooks   #
#                                 #
### =========================== ###

---
- name: Initial security configuration
  import_playbook: 00-initial.yml
- name: Base security
  import_playbook: 10-base-security.yml
